export interface RelationshipOption {
  code: string;
  englishLabel: string;
  gujaratiLabel: string;
  displayLabel: string; // "Father / પિતા"
  category: 'core' | 'extended' | 'in_law' | 'other';
  typicalGender?: 'Male' | 'Female';
  connectType?: 'spouse_of' | 'child_of' | 'parent_of' | 'none';
  connectPrompt?: string; // e.g. "Select the person they are related to"
  relationOf?: string; // e.g. "Spouse of", "Child of", "Parent of"
}

export const RELATIONSHIPS: RelationshipOption[] = [
  // Core
  {
    code: 'FAMILY_HEAD',
    englishLabel: 'Family Head',
    gujaratiLabel: 'પરિવાર વડા',
    displayLabel: 'Family Head / પરિવાર વડા',
    category: 'core',
    connectType: 'none',
  },
  {
    code: 'HUSBAND',
    englishLabel: 'Husband',
    gujaratiLabel: 'પતિ',
    displayLabel: 'Husband / પતિ',
    category: 'core',
    typicalGender: 'Male',
    connectType: 'spouse_of',
    connectPrompt: 'Select Wife (Whose Husband?) / પત્ની પસંદ કરો',
    relationOf: 'Husband of / ના પતિ',
  },
  {
    code: 'WIFE',
    englishLabel: 'Wife',
    gujaratiLabel: 'પત્ની',
    displayLabel: 'Wife / પત્ની',
    category: 'core',
    typicalGender: 'Female',
    connectType: 'spouse_of',
    connectPrompt: 'Select Husband (Whose Wife?) / પતિ પસંદ કરો',
    relationOf: 'Wife of / ની પત્ની',
  },
  {
    code: 'SON',
    englishLabel: 'Son',
    gujaratiLabel: 'દીકરો',
    displayLabel: 'Son / દીકરો',
    category: 'core',
    typicalGender: 'Male',
    connectType: 'child_of',
    connectPrompt: 'Select Parent (Whose Son?) / માતા અથવા પિતા પસંદ કરો',
    relationOf: 'Son of / ના દીકરા',
  },
  {
    code: 'DAUGHTER',
    englishLabel: 'Daughter',
    gujaratiLabel: 'દીકરી',
    displayLabel: 'Daughter / દીકરી',
    category: 'core',
    typicalGender: 'Female',
    connectType: 'child_of',
    connectPrompt: 'Select Parent (Whose Daughter?) / માતા અથવા પિતા પસંદ કરો',
    relationOf: 'Daughter of / ની દીકરી',
  },
  {
    code: 'SON_WIFE',
    englishLabel: 'Daughter-in-law (Son\'s Wife)',
    gujaratiLabel: 'વહુ (પુત્રવધૂ)',
    displayLabel: 'Daughter-in-law / વહુ (પુત્રવધૂ)',
    category: 'core',
    typicalGender: 'Female',
    connectType: 'spouse_of',
    connectPrompt: 'Whose Wife is she? (Select Husband) / કોની પત્ની છે? (પતિ પસંદ કરો)',
    relationOf: 'Wife of / ની પત્ની',
  },
  {
    code: 'DAUGHTER_HUSBAND',
    englishLabel: 'Son-in-law (Daughter\'s Husband)',
    gujaratiLabel: 'જમાઈ',
    displayLabel: 'Son-in-law / જમાઈ',
    category: 'core',
    typicalGender: 'Male',
    connectType: 'spouse_of',
    connectPrompt: 'Whose Husband is he? (Select Wife) / કોના પતિ છે? (પત્ની પસંદ કરો)',
    relationOf: 'Husband of / ના પતિ',
  },
  {
    code: 'FATHER',
    englishLabel: 'Father',
    gujaratiLabel: 'પિતા',
    displayLabel: 'Father / પિતા',
    category: 'core',
    typicalGender: 'Male',
    connectType: 'parent_of',
    connectPrompt: 'Select Child (Whose Father?) / સંતાન પસંદ કરો',
    relationOf: 'Father of / ના પિતા',
  },
  {
    code: 'MOTHER',
    englishLabel: 'Mother',
    gujaratiLabel: 'માતા',
    displayLabel: 'Mother / માતા',
    category: 'core',
    typicalGender: 'Female',
    connectType: 'parent_of',
    connectPrompt: 'Select Child (Whose Mother?) / સંતાન પસંદ કરો',
    relationOf: 'Mother of / ની માતા',
  },
  {
    code: 'BROTHER',
    englishLabel: 'Brother',
    gujaratiLabel: 'ભાઈ',
    displayLabel: 'Brother / ભાઈ',
    category: 'core',
    typicalGender: 'Male',
    connectType: 'none',
  },
  {
    code: 'SISTER',
    englishLabel: 'Sister',
    gujaratiLabel: 'બહેન',
    displayLabel: 'Sister / બહેન',
    category: 'core',
    typicalGender: 'Female',
    connectType: 'none',
  },
  {
    code: 'BROTHER_WIFE',
    englishLabel: "Brother's Wife (Bhabhi)",
    gujaratiLabel: 'ભાભી',
    displayLabel: "Brother's Wife / ભાભી",
    category: 'core',
    typicalGender: 'Female',
    connectType: 'spouse_of',
    connectPrompt: 'Whose Wife is she? (Select Brother) / કોની પત્ની છે? (ભાઈ પસંદ કરો)',
    relationOf: 'Wife of / ની પત્ની',
  },
  {
    code: 'SISTER_HUSBAND',
    englishLabel: "Sister's Husband (Banevi)",
    gujaratiLabel: 'બનેવી',
    displayLabel: "Sister's Husband / બનેવી",
    category: 'core',
    typicalGender: 'Male',
    connectType: 'spouse_of',
    connectPrompt: 'Whose Husband is he? (Select Sister) / કોના પતિ છે? (બહેન પસંદ કરો)',
    relationOf: 'Husband of / ના પતિ',
  },

  // Grandchildren
  {
    code: 'GRANDSON',
    englishLabel: 'Grandson (Poutra / Dohitra)',
    gujaratiLabel: 'પૌત્ર / દોહિત્ર',
    displayLabel: 'Grandson / પૌત્ર (પૌત્રીનો ભાઈ)',
    category: 'extended',
    typicalGender: 'Male',
    connectType: 'child_of',
    connectPrompt: 'Whose Son is he? (Select Father or Mother) / કોનો દીકરો છે? (માતા અથવા પિતા પસંદ કરો)',
    relationOf: 'Son of / ના દીકરા',
  },
  {
    code: 'GRANDDAUGHTER',
    englishLabel: 'Granddaughter (Poutri / Dohitri)',
    gujaratiLabel: 'પૌત્રી / દોહિત્રી',
    displayLabel: 'Granddaughter / પૌત્રી',
    category: 'extended',
    typicalGender: 'Female',
    connectType: 'child_of',
    connectPrompt: 'Whose Daughter is she? (Select Father or Mother) / કોની દીકરી છે? (માતા અથવા પિતા પસંદ કરો)',
    relationOf: 'Daughter of / ની દીકરી',
  },

  // Extended
  {
    code: 'ELDER_BROTHER',
    englishLabel: 'Elder Brother',
    gujaratiLabel: 'મોટા ભાઈ',
    displayLabel: 'Elder Brother / મોટા ભાઈ',
    category: 'extended',
    typicalGender: 'Male',
  },
  {
    code: 'YOUNGER_BROTHER',
    englishLabel: 'Younger Brother',
    gujaratiLabel: 'નાના ભાઈ',
    displayLabel: 'Younger Brother / નાના ભાઈ',
    category: 'extended',
    typicalGender: 'Male',
  },
  {
    code: 'ELDER_SISTER',
    englishLabel: 'Elder Sister',
    gujaratiLabel: 'મોટી બહેન',
    displayLabel: 'Elder Sister / મોટી બહેન',
    category: 'extended',
    typicalGender: 'Female',
  },
  {
    code: 'YOUNGER_SISTER',
    englishLabel: 'Younger Sister',
    gujaratiLabel: 'નાની બહેન',
    displayLabel: 'Younger Sister / નાની બહેન',
    category: 'extended',
    typicalGender: 'Female',
  },
  {
    code: 'BROTHER_SON',
    englishLabel: 'Nephew (Brother\'s Son)',
    gujaratiLabel: 'ભત્રીજો',
    displayLabel: "Brother's Son / ભત્રીજો",
    category: 'extended',
    typicalGender: 'Male',
    connectType: 'child_of',
    connectPrompt: 'Whose Son is he? (Select Brother) / કોનો દીકરો છે? (ભાઈ પસંદ કરો)',
    relationOf: 'Son of / ના દીકરા',
  },
  {
    code: 'BROTHER_DAUGHTER',
    englishLabel: 'Niece (Brother\'s Daughter)',
    gujaratiLabel: 'ભત્રીજી',
    displayLabel: "Brother's Daughter / ભત્રીજી",
    category: 'extended',
    typicalGender: 'Female',
    connectType: 'child_of',
    connectPrompt: 'Whose Daughter is she? (Select Brother) / કોની દીકરી છે? (ભાઈ પસંદ કરો)',
    relationOf: 'Daughter of / ની દીકરી',
  },
  {
    code: 'PATERNAL_GRANDFATHER',
    englishLabel: 'Paternal Grandfather (Dada)',
    gujaratiLabel: 'દાદા',
    displayLabel: 'Paternal Grandfather / દાદા',
    category: 'extended',
    typicalGender: 'Male',
  },
  {
    code: 'PATERNAL_GRANDMOTHER',
    englishLabel: 'Paternal Grandmother (Dadi)',
    gujaratiLabel: 'દાદી',
    displayLabel: 'Paternal Grandmother / દાદી',
    category: 'extended',
    typicalGender: 'Female',
  },
  {
    code: 'PATERNAL_UNCLE',
    englishLabel: 'Paternal Uncle (Kaka)',
    gujaratiLabel: 'કાકા',
    displayLabel: 'Paternal Uncle / કાકા',
    category: 'extended',
    typicalGender: 'Male',
  },
  {
    code: 'PATERNAL_AUNT',
    englishLabel: 'Paternal Aunt (Kaki)',
    gujaratiLabel: 'કાકી',
    displayLabel: 'Paternal Aunt / કાકી',
    category: 'extended',
    typicalGender: 'Female',
  },
  {
    code: 'MATERNAL_UNCLE',
    englishLabel: 'Maternal Uncle (Mama)',
    gujaratiLabel: 'મામા',
    displayLabel: 'Maternal Uncle / મામા',
    category: 'extended',
    typicalGender: 'Male',
  },
  {
    code: 'MATERNAL_AUNT',
    englishLabel: 'Maternal Aunt (Mami)',
    gujaratiLabel: 'મામી',
    displayLabel: 'Maternal Aunt / મામી',
    category: 'extended',
    typicalGender: 'Female',
  },
  {
    code: 'FATHER_S_SISTER',
    englishLabel: "Father's Sister (Foi)",
    gujaratiLabel: 'ફઈ',
    displayLabel: "Father's Sister / ફઈ",
    category: 'extended',
    typicalGender: 'Female',
  },
  {
    code: 'MOTHER_S_SISTER',
    englishLabel: "Mother's Sister (Masi)",
    gujaratiLabel: 'માસી',
    displayLabel: "Mother's Sister / માસી",
    category: 'extended',
    typicalGender: 'Female',
  },
  {
    code: 'OTHER',
    englishLabel: 'Other Relative',
    gujaratiLabel: 'અન્ય સંબંધ',
    displayLabel: 'Other / અન્ય',
    category: 'other',
  },
];

export function getRelationshipDisplay(code?: string | null): string {
  if (!code) return '';
  const found = RELATIONSHIPS.find((r) => r.code === code);
  return found ? found.displayLabel : code;
}
